config/routes.rb
Rails.application.routes.draw do
  get 'admin_dashboard/index'
  resources :posts
  devise_for :admins
  resources :posts
  get 'admin_dashboard', to: 'admin_dashboard#index'
  root to: 'pages#home'
  get 'services', to: 'pages#services'
  get 'meet', to: 'pages#meet'
  get 'contact', to: 'pages#contact'
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/admin_dashboard_controller.rb
class AdminDashboardController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, unless: :devise_or_public_pages?
  protect_from_forgery with: :exception
  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  private

  def devise_or_public_pages?
    devise_controller? || (params[:controller] == 'pages' && params[:action].in?(%w[home services]))
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:home, :services, :meet, :contact]

  def home
  end

  def services
  end

  def meet

  end

  def contact

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin_dashboard/index.html.erb
<div class="admin-top">
  <div class="admin-top-left">
    <%= image_tag 'admindash.jpg', alt: 'Cover photo for admin dashboard', class: 'dash-image' %>
  </div>
  <div class="admin-top-right">
    <h1>Amy & Nikki's Dashboard</h1>
    <%= link_to 'New Post', new_post_path, class: 'new-post-button' %>
  </div>
</div>


<%= link_to 'New Post', new_post_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 100) %></td>
        <td>
          <%= link_to 'Show', post_path(post) %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechniDesignStudios</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  crossorigin="anonymous"
/>


  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>

  <%= javascript_importmap_tags %>
</head>

<body>

  <%= render 'shared/navbar' %>

<div class="sign_in">
  <% if admin_signed_in? %>
    <%= link_to 'Dashboard', admin_dashboard_path, class: 'sign-in-button' %>
    <%= link_to 'Sign out', destroy_admin_session_path, method: :delete, class: 'sign-in-button' %>
  <% end %>
</div>


  <%= yield %>

    <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render 'shared/footer' %>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
  crossorigin="anonymous"
></script>



</body>
</html>

app/views/pages/contact.html.erb
<div class="contact-container">
  <div class="contact-left">
    <p>/WHERE TO FIND US</p>
    <h1 class="bigger-h1">Say Hi!</h1>
    <p>Ready to bring your ideas to life? <br>
      Get in touch with us - we'd love to hear from you and help <br>
      create something extraordinary together.</p>
    <p>Email us at: <br>
      hello@technidesignstudios.com</p>
  </div>
  <div class="contact-right">
    <h1>contact form here</h1>
  </div>
</div>

app/views/pages/home.html.erb
<div class="top-container">

    <div class="top-container-left">
      <p>/WE ARE TECHNI</p>
      <div data-controller="hello"></div>

      <h1 class="bigger-h1">Web design & <br> graphic design is our <br> area of expertise</h1>
      <p id="top-container-p">We're on a mission to make you feel awesome in web and print.</p>
      <div class="top-section-buttons">
        <a class="get-a-quote" href="#">Get A Quote</a>
        <a id="view-our-work" href="#">View Our Work</a>
      </div>
    </div>
    <div class="top-container-right">
        <%# <h1>temp placeholder for now</h1> %>
    </div>
  </div>

  <div class="second-container">

    <div class="container-left sticky-left">
      <h2 class="bigger-h2">We strive to understand <br> you and your goals.</h2>
    </div>
    <div class="container-right scrollable-right">
        <%= image_tag 'design-icon.svg', alt: 'topicon', class: 'thumbnail' %>
        <h4>Design</h4>
        <p>Your identity represents your brand and what you stand for. Get it right and it can help you attract and connect
        with your customers. Whether you are a startup or a well established brand, we can help.
        </p>
        <ul class="square-list">
          <li>Branding</li>
          <li>ATS Friendly CV</li>
          <li>Print</li>
          <li>Illustration</li>
        </ul>
        <%= image_tag 'digital-icon.svg', alt: 'bottomicon', class: 'thumbnail' %>
        <h4>Digital</h4>
        <p>We design and develope websites that present your brand in the best way possible. From research and strategy, to
        design and development, our websites are simple, reliable, user friendly and built to achieve your goals.
        </p>
          <ul class="square-list">
            <li>Web design</li>
            <li>Web development</li>
        </ul>
    </div>
  </div>

  <div class="third-container">
    <div class="container-left sticky-left">
      <h2 class="bigger-h2">We're a compact team <br> with diverse talents.</h2>
    </div>
    <div class="container-right scrollable-right">
      <%= image_tag 'nikki.png', alt: 'avatar', class: 'profile-mini' %>
      <h4>Nikki</h4>
      <p>Nikki is a skilled developer with a nack for turning complex concepts into seamless digital solutions. With a deep
      understanding of web technologies and a commitment to functionality, she brings projects to life with clean, efficient code.
      Nikki's expertise ensures that every design performs flawlessly, delivering a user experience that's both intuitive and
      robust. Her approach combines technical precision with a thoughtful, client-focussed process.
      </p>
       <%= image_tag 'amy.png', alt: 'avatar', class: 'profile-mini' %>
      <h4>Amy</h4>
      <p>An experienced designer with a passion for creating user-centered digital experiences, Amy brings a unique blend
      of creativity and technical precision to every project. Known for her eye for detail and commitment to quality, Amy
      specialises in specialises in building visually compelling, intuitive designs that elevate brands and engage audiences.
      From brand identity to responsive web design, Amy is dedicated to transforming ideas into polished, impactful visuals
      tailored to each client's needs.
      </p>
    </div>
  </div>

    <%= image_tag 'cover-print.png', alt: 'Descriptive alt text', class: 'cover-print' %>

  <div class="fouth-container scrollable-right">
      <div class="portfolio-wrapper">
        <h1>Designs that define us</h1>
        <div class="portfolio-container">
          <div class="portfolio-card">
            <%= image_tag 'portfolio-website.png', alt: 'portfolio pic', class: 'portfolio-pic' %>
            <h4>Portfolio Website</h4>
            <p>Online Portfolio Up To 5 Pages</p>
            <p>Optional Customn CV Design</p>
          </div>
          <div class="portfolio-card">
            <%= image_tag 'web-design.png', alt: 'portfolio pic', class: 'portfolio-pic' %>
            <h4>Website Design & Development</h4>
            <p>Web Design & Development</p>
            <p>Basic On Site SEO</p>
          </div>
          <div class="portfolio-card">
            <%= image_tag 'premade-temp.png', alt: 'portfolio pic', class: 'portfolio-pic' %>
            <h4>Premade Template</h4>
            <p>We have a small selection of templates which are perfect if you are <br> in a hurry to get going</p>
          </div>
          <div class="portfolio-card">
            <%= image_tag 'cv-portfolio.png', alt: 'portfolio pic', class: 'portfolio-pic' %>
            <h4>CV & Portfolio</h4>
            <p>One Page Website</p>
            <p>Downloadable Custom CV Design</p>
          </div>
        </div>
      </div>
  </div>

  <div class="fifth-container">
    <h1>Loved <br> & Trusted</h1>
      <div class="review-container">
        <div class="review-card">
          <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"</p>
          <p>Person Name</p>
          <p>Project Name</p>
        </div>
        <div class="review-card">
          <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"</p>
          <p>Person Name</p>
          <p>Project Name</p>
        </div>     <div class="review-card">
          <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"</p>
          <p>Person Name</p>
          <p>Project Name</p>
        </div>
        <div class="review-card">
          <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"</p>
          <p>Person Name</p>
          <p>Project Name</p>
        </div>
        <div class="review-card">
          <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"</p>
          <p>Person Name</p>
          <p>Project Name</p>
        </div>
        <div class="review-card">
          <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"</p>
          <p>Person Name</p>
          <p>Project Name</p>
        </div>
      </div>
  </div>

  <div class="bottom-container">
    <div class="project-callout">
      <span class="main-text">Have a project in mind?</span>
      <span class="reveal-text"> get in touch</span>
    </div>

    <div class="center-wrapper">
      <a class="get-in-touch" href="#">Get In Touch</a>
    </div>
  </div>

app/views/pages/meet.html.erb
<div class="meet-top">
  <p>/MEET THE TEAM</p>
  <h1 class="bigger-h1">Welcome to Techni Design <br>
  Studios</h1>
    <div class="meet-top-text">
    <p>From the open seas to the digital world, Amy <br>
    and Nikki bring a unique blend of creativity, <br>
    precision, and teamwork honed as former yacht<br>
    chefs. Now, they channel that same dedication <br>
    into web design and development, crafting <br>
    beautifully designed, high-performing websites</p>

    <p>that work as smoothly as they look. With Amy's <br>
    keen eye for design and Nikki's technical  <br>
    expertise, they're here to make your brand <br>
    stand out with style and reliability. Clients can <br>
    trust them to handle the heat - whether it's in<br>
    the kitchen or in their next project.</p>
  </div>
</div>

<div class="meet-second">

</div>

<div class="meet-amy-nikki">
  <div class="meet-left">
    <h1 class="bigger-h1">MEET NIKKI</h1>
    <br>
    <h5>The Tech Wizz</h5>
    <p>Nikki is a skilled developer with a nack for turning <br>
      complex concepts into seamless digital solutions. <br>
      With a deep understanding of web technologies and <br>
      a commitment to functionality , she brings project to <br>
      life with clean, efficient code. Nikki's expertise <br>
      ensures that every design performs flawlessly, <br>
      delivering a user experience that's both intuitive and <br>
      robust. Her approach combines technical precision <br>
      with a thoughtful, client-focused process.
    </p>
  </div>

  <div class="meet-right">
    <%= image_tag "nikki.png", alt: "Profile photo of Nikki", class: "meet-profile" %>
  </div>
</div>

<%= image_tag "meet-strip.png", alt: "Strip of photos showing previous projects", class: "meet-strip" %>

<div class="meet-amy-nikki">
  <div class="meet-left">
    <%= image_tag "amy.png", alt: "Profile photo of Amy", class: "meet-profile" %>
  </div>
  <div class="meet-right">
    <h1 class="bigger-h1">MEET AMY</h1>
    <br>
    <h5>The Design Guru</h5>
    <p>An experienced designer with a passion for creating <br>
      user centered digital experiences. Amy brings a <br>
      unique blend of creativity and technical precision to <br>
      every project. Known for her eye for detail and <br>
      commitment to quality. Amy specializes in building<br>
      visually compelling, intuitive designs that elevate <br>
      brands and engage audiences. From brand identity <br>
      to responsive web design, Amy is dedicated to<br>
      transforming ideas into polished, impactful visuals <br>
      tailored to each client's needs.
    </p>
    </div>
</div>

<div class="bottom-container">
  <div class="project-callout">
    <span class="main-text">Have a project in mind?</span>
    <span class="reveal-text"> get in touch</span>
  </div>

  <div class="center-wrapper">
    <a class="get-in-touch" href="#">Get In Touch</a>
  </div>
</div>

app/views/pages/services.html.erb
<div class="services-top">
  <p>/OUR SERVICES</p>
  <h1 class="bigger-h1">Future Proof Your digital <br>
  Presence.</h1>
  <div class="services-top-text">
    <p>At Techni Design Studios, we're all about <br>
    transforming ideas into exceptional digital <br>
    experiences. With a seamless blend of eye- <br>
    catching design and rock-solid development, <br>
    our services are crafted to meet the unique <br>
    needs of each client. From building your brand</p>

    <p>identity to developing a responsive, engaging <br>
    website. We're are here to help you stand out in <br>
    today's digital landscape. Dive into our <br>
    offerings and discover how we can bring your <br>
    vision to life-reliably, creatively, and with a <br>
    personal touch honed by years of experience.</p>
  </div>
</div>

<div class="services-second">
  <%= image_tag "services-cover.png", alt: "Cover photo of some of our designs", class: "services-cover" %>
</div>

<div class="services-third">
  <div class="title-text">
    <h1 class="services-third-left bigger-h1 purple-outline">Website Design & <br> Developement</h1>
    <p class="services-third-right">Let us craft a website that's beautiful, <br>
      functional, and built to support your goals, with <br>
      thoughtful design, smooth development and <br>
      essential SEO. </p>
  </div>
  <div class="services-accordian">
        <div class="accordion-container">
          <div class="accordion-item">
            <div class="accordion-header" data-target="#content-1">
              <span class="heading">One-Page Website</span>
              <span class="plus">+</span>
            </div>
            <div class="accordion-content" id="content-1">
              <h5>Perfect for startups, CV sites, or personal brands</h5>
              <p>Our one-page website offers a sleek, custom-designed layout to elegantly showcase your brand or services.</p>
              <h5>Package Includes:</h5>
              <ul>
                <li>Responsive design optimized for all devices</li>
                <li>Basic SEO setup for better online visibility</li>
                <li>A contact form and integrated social media links</li>
              </ul>
            </div>
          </div>

          <div class="accordion-item">
            <div class="accordion-header" data-target="#content-2">
              <span class="heading">Starter Site</span>
              <span class="plus">+</span>
            </div>
            <div class="accordion-content" id="content-2">
              <h5>Tailored for professionals and creatives</h5>
              <p>Highlight your skills and achievements with a custom-built CV or portfolio website designed to leave a lasting impression.</p>
              <h5>Package Includes:</h5>
              <ul>
                <li>Up to three pages, including a downloadable PDF CV</li>
                <li>Responsive design for seamless access on any device</li>
                <li>LinkedIn profile integration for a polished online presence</li>
              </ul>
            </div>
          </div>

          <div class="accordion-item">
            <div class="accordion-header" data-target="#content-3">
              <span class="heading">Five-Page Site</span>
              <span class="plus">+</span>
            </div>
            <div class="accordion-content" id="content-3">
              <h5>Ideal for growing businesses</h5>
              <p>Create a comprehensive online platform for your business with advanced design features and enhanced functionality.</p>
              <h5>Package Includes:</h5>
              <ul>
                <li>Custom design tailored to your brand</li>
                <li>Blog setup and CMS integration for easy updates</li>
                <li>Social media integration and basic SEO setup to connect with your audience</li>
              </ul>
            </div>
          </div>


    </div>
  </div>
</div>

<div class="services-fourth">
  <%= image_tag "services-placeholder.png", alt: "Cover photo of some of our designs", class: "services-placeholder" %>
</div>

<div class="services-fifth">
  <div class="title-text">
    <h1 class="services-fifth-left bigger-h1 purple-outline">Brand Design & <br> Strategy</h1>
    <p class="services-fifth-right">Let us help you tell your story in a way that's <br>
    memorable, impactful, and designed to grow <br>
    with you</p>
  </div>
  <div class="services-accordian">
    <div class="accordion-container">

          <div class="accordion-item">
            <div class="accordion-header" data-target="#content-4">
              <span class="heading">Brand Identity Essentials</span>
              <span class="plus">+</span>
              </div>
              <div class="accordion-content" id="content-4">
                <h5>Build the foundation of your brand</h5>
                <p>This package is perfect for startups or businesses looking to establish their visual identity.</p>
                <h5>Package Includes:</h5>
                <ul>
                  <li>Logo design (primary, secondary, and icon)</li>
                  <li>Brand color palette</li>
                  <li>Typography selection</li>
                  <li>Basic brand guidelines</li>
                </ul>
              </div>
          </div>

          <div class="accordion-item">
            <div class="accordion-header" data-target="#content-5">
              <span class="heading">Brand Identity Plus</span>
              <span class="plus">+</span>
              </div>
              <div class="accordion-content" id="content-5">
                <h5>Elevate your brand’s presence</h5>
                <p>Take your branding to the next level with additional assets to create a cohesive and professional look across all platforms.</p>
                <h5>Package Includes:</h5>
                <ul>
                  <li>Everything in the Brand Identity Essentials package</li>
                  <li>Business card design</li>
                  <li>Social media profile and post templates</li>
                  <li>Email signature design</li>
                </ul>
              </div>
          </div>

          <div class="accordion-item">
            <div class="accordion-header" data-target="#content-6">
              <span class="heading">Custom Brand Strategy</span>
              <span class="plus">+</span>
              </div>
              <div class="accordion-content" id="content-6">
                <h5>Define your unique voice and vision</h5>
                <p>Work with us to create a detailed strategy that aligns your brand with your target audience.</p>
                <h5>Package Includes:</h5>
                <ul>
                  <li>Brand discovery session</li>
                  <li>Target audience and competitor analysis</li>
                  <li>Brand messaging and tone of voice guide</li>
                  <li>Mission, vision, and tagline development</li>
                </ul>
              </div>
          </div>

          <div class="accordion-item">
            <div class="accordion-header" data-target="#content-7">
              <span class="heading">Rebranding Package</span>
              <span class="plus">+</span>
              </div>
              <div class="accordion-content" id="content-7">
                <h5>Refresh and modernize your identity</h5>
                <p>Ideal for businesses looking to pivot or update their look to reflect growth and new goals.</p>
                <h5>Package Includes:</h5>
                <ul>
                  <li>Logo redesign</li>
                  <li>Updated color palette and typography</li>
                  <li>Revamped brand guidelines</li>
                  <li>Audit of current brand assets</li>
                </ul>
              </div>
          </div>

    </div>
  </div>
</div>

<div class="bottom-container">
  <div class="project-callout">
    <span class="main-text">Have a project in mind?</span>
    <span class="reveal-text"> get in touch</span>
  </div>

  <div class="center-wrapper">
    <a class="get-in-touch" href="#">Get In Touch</a>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    document.querySelectorAll(".accordion-header").forEach(header => {
      header.addEventListener("click", () => {
        const targetId = header.getAttribute("data-target");
        const content = document.querySelector(targetId);
        content.classList.toggle("active");
      });
    });
  });
</script>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/shared/_footer.html.erb
<div class="top-footer">
  <%# <%= image_tag 'logo.png', alt: 'logo', class: 'techni-logo' %> %>
    <div class="list-container">
        <ul class="footer-lists no-bullets">
          <li>Product</li>
            <br>
          <li><strong>Services</strong></li>
          <li><strong>Packages</strong></li>
          <li><strong>Book a Call</strong></li>
        </ul>
        <ul class="footer-lists no-bullets">
          <li>Explore</li>
            <br>
          <li><strong>Blog</strong></li>
        </ul>
        <ul class="footer-lists no-bullets">
          <li>Company</li>
            <br>
          <li><strong>About Us</strong></li>
          <li><strong>Contact Us</strong></li>
        </ul>
    </div>
</div>

<div class="bottom-footer">
  <p class="footer-item">2024 Techni Design Studios.</p>
  <p class="footer-item">Privacy Policy.</p>
  <p class="footer-item">Terms of Service</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-custom">
  <div class="container-fluid d-flex align-items-center">
    <!-- Logo -->
    <%= link_to root_path do %>
      <%= image_tag 'logo-nav.svg', alt: 'logo', class: 'techni-little-logo' %>
    <% end %>

    <!-- Burger Menu Button -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible Menu -->
    <div class="collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link custom-nav-link" href="<%= services_path %>">SERVICES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link custom-nav-link" href="<%= meet_path %>">MEET THE TEAM</a>
        </li>
        <li class="nav-item">
          <a class="nav-link custom-nav-link" href="<%= contact_path %>">CONTACT US</a>
        </li>
        <li class="nav-item">
          <a class="nav-link custom-nav-link" href="#contact">CONTACT</a>
        </li>
      </ul>
    </div>
  </div>
</nav>